### ISSUE TITLE
Is is safe to upstream the hdptxphy_hdmi_clk?

### ISSUE THREAD

**Issue by nyanmisaka** [amazingfate/radxa-rock5b-overlays#1]
Thanks for this fix! The `hdptxphy_hdmi_clk` overlay is essential for the 1440p hdmi display on Rock-5b.

Many users including me are facing the same issue.
https://forum.radxa.com/t/ubuntu-image-with-x11-and-resolution-2560x1440/

Is it safe to upstream this to the radxa or armbian repo without producing other regressions?

**Comment by amazingfate** [comment]
I didn't take too much test. Maybe you can create a pull request to radxa's kernel repo.

**Comment by nyanmisaka** [comment]
Thanks, i will try.
